import type { Theme } from '../../types/theme';

export const gruvboxLight: Theme = {
  id: 'gruvbox-material-light',
  name: 'Gruvbox Material Light',
  author: 'sainnhe',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#fbf1c7',
      elevated: '#f2e5bc',
      overlay: '#ebdbb2',
      input: '#fbf1c7',
      tooltip: '#f2e5bc',
    },
    surface: {
      primary: '#f2e5bc',
      secondary: '#ebdbb2',
      tertiary: '#e0cfa9',
      hover: '#eee0b7',
      active: '#d5c4a1',
      disabled: '#f2e5bc',
    },
    text: {
      primary: '#463125',
      secondary: '#4f3829',
      muted: '#6a5f56',
      disabled: '#a89984',
      accent: '#5c6627',
      inverse: '#fbf1c7',
    },
    accent: {
      primary: '#68732c',
      secondary: '#436d77',
      success: '#616c29',
      warning: '#915b07',
      error: '#b43e3e',
      info: '#436d77',
    },
    border: {
      subtle: '#ebdbb2',
      default: '#e0cfa9',
      strong: '#c9b99a',
      focus: '#6c782e',
    },
    semantic: {
      string: '#915b07',
      number: '#895777',
      boolean: '#895777',
      date: '#467055',
      null: '#736552',
      primaryKey: '#a34f08',
      foreignKey: '#436d77',
      index: '#895777',
      connectionActive: '#6c782e',
      connectionInactive: '#a89984',
      modified: '#436d77',
      deleted: '#b43e3e',
      new: '#616c29',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, sans-serif',
      mono: 'Menlo, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs',
    inherit: true,
    themeName: 'Gruvbox Material Light',
  },
};
