import type { Theme } from '../../types/theme';

export const tabularisLight: Theme = {
  id: 'tabularis-light',
  name: 'Tabularis Light',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#ffffff',
      elevated: '#f8fafc',
      overlay: '#f1f5f9',
      input: '#ffffff',
      tooltip: '#f1f5f9',
    },
    surface: {
      primary: '#f1f5f9',
      secondary: '#e2e8f0',
      tertiary: '#cbd5e1',
      hover: '#e2e8f0',
      active: '#3b82f6',
      disabled: '#f1f5f9',
    },
    text: {
      primary: '#0f172a',
      secondary: '#475569',
      muted: '#5b697e',
      disabled: '#94a3b8',
      accent: '#0b5ee7',
      inverse: '#ffffff',
    },
    accent: {
      primary: '#1e6ff5',
      secondary: '#8250f5',
      success: '#17843f',
      warning: '#a06707',
      error: '#e51414',
      info: '#047e92',
    },
    border: {
      subtle: '#f1f5f9',
      default: '#e2e8f0',
      strong: '#cbd5e1',
      focus: '#3b82f6',
    },
    semantic: {
      string: '#dc2626',
      number: '#2563eb',
      boolean: '#7c3aed',
      date: '#12853c',
      null: '#64748b',
      primaryKey: '#ae5f05',
      foreignKey: '#077d9a',
      index: '#9333ea',
      connectionActive: '#22c55e',
      connectionInactive: '#64748b',
      modified: '#186bf4',
      deleted: '#e51414',
      new: '#17843f',
    },
  },
  typography: {
    fontFamily: {
      base: 'Inter, system-ui, Avenir, Helvetica, Arial, sans-serif',
      mono: 'JetBrains Mono, Fira Code, Monaco, Consolas, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs',
    inherit: true,
    themeName: 'GitHub Light',
  },
};
